version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pwd123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3310:3306'
    expose:
      # Opens port 3306 on the container
      - '3310'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  cache:
    image: redis:latest
    command: redis-server --requirepass pwd123
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
# Names our volume
volumes:
  my-db: 
  cache: